### PR TITLE
Add Wallet to Wallet connections

### PR DESCRIPTION
**Pull request by rodolfomiranda**

### CODE REVIEW

**Comment by rodolfomiranda** [comment]
> 

I did not change anything regarding prism sdk. The error is clear, by the way. But I think that @2byrds remove the JS sdk from the code. Try removing `@input-output-hk/atala-prism-sdk": "^1.4.1"` from package.json

**Comment by 2byrds** [comment]
> > 
> 
> I did not change anything regarding prism sdk. The error is clear, by the way. But I think that @2byrds removed JS sdk dependencies from the code. Try removing `@input-output-hk/atala-prism-sdk": "^1.4.1"` from package.json

great point!  likely it's been taken down and removing it should be good... i don't recall where i removed it before, maybe this branch.... checking now will report back soon :)

**Comment by 2byrds** [comment]
I had removed it here https://github.com/roots-id/rootswallet/pull/110

**Comment by rodolfomiranda** [comment]
> I had removed it here #110

So I added without intention in my PR :)

**Comment by 2byrds** [comment]
> > I had removed it here #110
> 
> So I added without intention in my PR :)

I think you still have it in your branch, can you rebase with main.  if you take the PR out of draft i think it will tell you to rebase first. https://github.com/roots-id/rootswallet/blob/106-wallet-to-wallet-connections/package.json#L24

**Comment by 2byrds** [comment]
> > > I had removed it here #110
> > 
> > 
> > So I added without intention in my PR :)
> 
> I think you still have it in your branch, can you rebase with main. if you take the PR out of draft i think it will tell you to rebase first. https://github.com/roots-id/rootswallet/blob/106-wallet-to-wallet-connections/package.json#L24

i updated via the github editor, pretty great tool! i'll test it now.  try updating @AlexAndrei98 for your testing.

**Comment by 2byrds** [comment]
I was unable to use the cameras from my emulator https://github.com/roots-id/rootswallet/issues/113. But @rodolfomiranda has a video he can include on this PR and @AlexAndrei98 confirmed it worked for him.

**Pull request merged**
